/** Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Staff;

import java.awt.Color;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Ayush
 *
 */
import java.sql.*;

public class Record_Employee extends javax.swing.JInternalFrame {

    ResultSet rs;
    connect c;
    String sql, r1;
    int list, row;
    DefaultTableModel model;

    /**
     * Creates new form Record_Employee
     */
    public Record_Employee() {
        initComponents();
        c = new connect();
        c.getConnect();
        jPanel3.setVisible(true);
        jPanel5.setVisible(false);
        jPanel7.setVisible(false);
        jTextField3.setVisible(false);

//        this.setLocationRelativeTo(null);
        data("");
    }

    void data(String empid) {
        try {
            sql = "select * from v2 order by empid";
            model = (DefaultTableModel) jTable1.getModel();
            System.out.println(sql);
            int row = jTable1.getRowCount();
            if (row > 0) {
                for (int i = row - 1; i >= 0; i--) {
                    model.removeRow(i);
                }
            }
            rs = c.s.executeQuery(sql);
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(9), rs.getString(10), rs.getString(12), rs.getString(7), rs.getString(11)});
            }
            jLabel3.setText("TOTAL RECORDS ARE :" + jTable1.getRowCount());
            System.out.println(model);

        } catch (Exception e) {
            jOptionPane1.showMessageDialog(this, "Error" + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SEARCH RECORD AS YOUR PREFERENCES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 3, 18))); // NOI18N

        jButton1.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jButton1.setText("FILTER");
        jButton1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jButton1StateChanged(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jButton2.setText("SEARCH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jButton4.setText("SHOW ALL");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jButton5.setText("RESET");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel2.setText("ADDRESS   :");

        jTextField1.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel1.setText("FULLNAME :");

        jTextField2.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });

        jTextField3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RECORD OF THE EMPLOYEES : ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 3, 18))); // NOI18N

        jTable1.setBackground(new java.awt.Color(102, 102, 102));
        jTable1.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NAME", "EMAIL", "CONTACT", "DEPARTMENT", "JOB ", "STATUS", "ADDRESS", "SALARY"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel3.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1094, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MORE FILTER ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 3, 14))); // NOI18N

        jList1.setBackground(new java.awt.Color(204, 204, 204));
        jList1.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "EMPLOYEE ID ", "SALARY", "JOB", "GENDER", "DEPARTMENT", "JOB_STATUS", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CHOOSE ANY OPTIONS:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 3, 14))); // NOI18N

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jRadioButton4.setText("jRadioButton1");

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jRadioButton5.setText("jRadioButton1");

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jRadioButton6.setText("jRadioButton1");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jRadioButton7.setText("jRadioButton1");

        buttonGroup1.add(jRadioButton8);
        jRadioButton8.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jRadioButton8.setText("jRadioButton1");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jRadioButton3.setText("jRadioButton1");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jRadioButton2.setText("jRadioButton1");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jRadioButton1.setText("jRadioButton1");
        jRadioButton1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jRadioButton1FocusLost(evt);
            }
        });
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseClicked(evt);
            }
        });
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jButton3.setText("APPLY");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jRadioButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jRadioButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jRadioButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jRadioButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jRadioButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jRadioButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 317, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String fullname = jTextField1.getText();
        String address = jTextField2.getText();
        through_fullname(fullname);
        through_Address(address);
    }//GEN-LAST:event_jButton2ActionPerformed
    public void filtration() {
        try {
            String filter = jList1.getSelectedValue();
            jPanel5.setVisible(true);
            if (jList1.isSelectedIndex(1)) {
                jLabel1.setText("FULLNAME");
            } else if (jList1.isSelectedIndex(2)) {
                jLabel1.setText("EMAIL");
            } else if (jList1.isSelectedIndex(3)) {
                jLabel1.setText("ADDRESS");
            }

        } catch (Exception e) {
            jOptionPane1.showMessageDialog(this, "Error is :" + e, "Error!!", 0);
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            jPanel5.setVisible(true);
        } catch (Exception e) {
            jOptionPane1.showMessageDialog(this, "Error is :" + e, "Error!!", 0);
        }

    }//GEN-LAST:event_jButton1ActionPerformed
    public void visible() {
        jRadioButton4.setVisible(true);
        jRadioButton5.setVisible(true);
        jRadioButton6.setVisible(true);
        jRadioButton7.setVisible(true);
        jRadioButton8.setVisible(true);
    }
    private void jButton1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jButton1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1StateChanged
    public void clear() {
        int list = jList1.getSelectedIndex();
        if (list == 0) {
            jRadioButton1.setText(null);
            jRadioButton2.setText(null);
            jRadioButton3.setText(null);
            jRadioButton4.setText(null);
            jRadioButton5.setText(null);
            jRadioButton6.setText(null);
            jRadioButton7.setText(null);
            jRadioButton8.setText(null);
        }
    }
    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        try {
            list = jList1.getSelectedIndex();
            if (list == 0) {
                visible();
//                jPanel6.setSize(984, 43);
                jPanel7.setVisible(false);
                jLabel2.setVisible(false);
                jTextField1.setVisible(false);
                jTextField2.setVisible(false);
                jTextField3.setVisible(true);
                jLabel1.setText("EMPLOYEE ID :");
                jTextField3.setText("");
                if (evt.isPopupTrigger()) {
                    jTextField1.setText("");
                }
                jTextField1.setForeground(Color.GRAY);
                jTextField1.requestFocus();
            } else if (list == 1) {
                visible();
                jPanel7.setVisible(true);
                jLabel2.setVisible(true);
                jLabel1.setText("EMAIL");
                jLabel2.setText("ADDRESS");
                jTextField3.setVisible(false);
                jTextField1.requestFocus();
                jTextField1.setForeground(Color.BLACK);
                jTextField1.setText("");
                jTextField1.setVisible(true);
                jTextField2.setVisible(true);
                jPanel6.setSize(984, 43);
                jRadioButton1.setText("SALARY<400000");
                jRadioButton2.setText("SALARY>400000 AND SALARY<800000");
                jRadioButton3.setText("SALARY>800000 AND SALARY<1200000");
                jRadioButton4.setText("SALARY>1200000 AND SALARY<1600000");
                jRadioButton5.setText("SALARY>1600000 AND SALARY<2000000");
                jRadioButton6.setText("SALARY>2000000 AND SALARY<2400000");
                jRadioButton7.setText("SALARY>2400000 AND SALARY<3000000");
                jRadioButton8.setVisible(false);
            } else if (list == 2) {
                visible();
                jPanel7.setVisible(true);
                jLabel2.setVisible(true);
                jLabel1.setText("EMAIL");
                jLabel2.setText("ADDRESS");
                jTextField3.setVisible(false);
                jTextField1.requestFocus();
                jTextField1.setText("");
                jTextField2.setVisible(true);
                jTextField1.setVisible(true);
                jPanel6.setSize(984, 43);
                jRadioButton8.setVisible(true);
                jRadioButton1.setText("DATA SCIENTIST");
                jRadioButton2.setText("PRODUCT MANAGER");
                jRadioButton3.setText("TECHNICAL SUPPORT ENGINEER");
                jRadioButton4.setText("CLOUD SOLUTIONS ARCHITECT");
                jRadioButton5.setText("RESEARCH SCIENTIST");
                jRadioButton6.setText("SALES SPECIALIST");
                jRadioButton7.setText("MARKETING MANAGER");
                jRadioButton8.setText("UX DESIGNER");
            } else if (list == 3) {
                jPanel7.setVisible(true);
//                jPanel7.setSize(100, 100);
                jLabel2.setVisible(true);
                jLabel1.setText("EMAIL");
                jLabel2.setText("ADDRESS");
                jTextField3.setVisible(false);
                jTextField1.requestFocus();
                jTextField1.setText("");
                jTextField2.setVisible(true);
                jTextField1.setVisible(true);
//                jPanel6.setSize(984, 43);
                jRadioButton1.setText("MALE");
                jRadioButton2.setText("FEMALE");
                jRadioButton3.setText("OTHERS");
                jRadioButton4.setVisible(false);
                jRadioButton5.setVisible(false);
                jRadioButton6.setVisible(false);
                jRadioButton7.setVisible(false);
                jRadioButton8.setVisible(false);
            } else if (list == 4) {
                visible();
                jPanel7.setVisible(true);
                jLabel2.setVisible(true);
                jLabel1.setText("EMAIL");
                jLabel2.setText("ADDRESS");
                jTextField3.setVisible(false);
                jTextField1.requestFocus();
                jTextField1.setText("");
                jTextField2.setVisible(true);
                jTextField1.setVisible(true);
                jPanel6.setSize(984, 43);
//                jPanel7.setSize(100, 100);
                jRadioButton1.setText("PRODUTIVITY PROCESSES");
                jRadioButton2.setText("BUSINESSES PROCESSES");
                jRadioButton3.setText("INTELLIGENT CLOUD");
                jRadioButton4.setText("PERSONAL COMPUTING");
                jRadioButton5.setText("CLOUD AND ARTIFICIAL INTELLIGENCE");
                jRadioButton6.setText("EXPERIECES AND PROCESSES");
                jRadioButton7.setText("GAMING");
                jRadioButton8.setText("TECHNOLOGIES AND RESEARCH");
            } else if (list == 5) {
                visible();
                jTextField1.requestFocus();
                jRadioButton1.setText("FULL TIME");
                jRadioButton2.setText("PART TIME");
                jRadioButton3.setText("INTERN");
                jRadioButton4.setText("REMOTE");
                jRadioButton5.setText("FORMER");
                jRadioButton6.setText("TEMPORARY");
                jRadioButton7.setText("CONTRACTOR");
                jRadioButton8.setVisible(false);

            }
        } catch (Exception e) {
            jOptionPane1.showMessageDialog(this, "Error" + e, "Error!!", 0);
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
    void through_empid(int empid) {
        try {
            empid = Integer.parseInt(jTextField3.getText());
            sql = "Select * from v2 where empid= "+ empid ;
            System.out.println(sql);
            model = (DefaultTableModel) jTable1.getModel();
            row = jTable1.getRowCount();
            if (row > 0) {
                for (int i = row - 1; i >= 0; i--) {
                    model.removeRow(i);
                }
            }
            rs =c.s.executeQuery(sql);
            System.out.println(sql);
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(9), rs.getString(10), rs.getString(12), rs.getString(7), rs.getString(11)});
            }
            jLabel3.setText("TOTAL RECORDS ARE :" + jTable1.getRowCount());
            data(r1);
        } catch (SQLException e) {
            jOptionPane1.showMessageDialog(this, "Error is" + e, "Error", 0);
        }
    }

    void through_salary(String r1) {
        try {
            sql = "Select  * from v2 where " + r1 + "";
            System.out.println(sql);
            model = (DefaultTableModel) jTable1.getModel();
            row = jTable1.getRowCount();
            if (row > 0) {
                for (int i = row - 1; i >= 0; i--) {
                    model.removeRow(i);
                }
            }
            rs =  c.s.executeQuery(sql);
            System.out.println(sql);
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(9), rs.getString(10), rs.getString(12), rs.getString(7), rs.getString(11)});
            }
            jLabel3.setText("TOTAL RECORDS ARE :" + jTable1.getRowCount());
//            data(r1);
        } catch (SQLException e) {
            jOptionPane1.showMessageDialog(this, "Error is" + e, "Error", 0);
        }
    }

    void through_job(String r1) {

        try {
            sql = "Select * from v2 where jobname= '" + r1 + "'";
            System.out.println(sql);
            model = (DefaultTableModel) jTable1.getModel();
            row = jTable1.getRowCount();
            if (row > 0) {
                for (int i = row - 1; i >= 0; i--) {
                    model.removeRow(i);
                }
            }
            rs =c.s.executeQuery(sql);
            System.out.println(sql);
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(9), rs.getString(10), rs.getString(12), rs.getString(7), rs.getString(11)});
            }
            jLabel3.setText("TOTAL RECORDS ARE :" + jTable1.getRowCount());
//            data(r1);
        } catch (SQLException e) {
            jOptionPane1.showMessageDialog(this, "Error is" + e, "Error", 0);
        }
    }

    void through_Address(String address) {
        try {
//            address = jTextField2.getText();
            sql = "Select * from v2 where address like '" + address + "'";
            System.out.println(sql);
            model = (DefaultTableModel) jTable1.getModel();
            row = jTable1.getRowCount();
            if (row > 0) {
                for (int i = row - 1; i >= 0; i--) {
                    model.removeRow(i);
                }
            }
            rs =c.s.executeQuery(sql);
            System.out.println(sql);
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(9), rs.getString(10), rs.getString(12), rs.getString(7), rs.getString(11)});
            }
            jTable1.getRowCount();
//            data(address);
        } catch (SQLException e) {
            jOptionPane1.showMessageDialog(this, "Error is" + e, "Error", 0);
        }
    }

    void through_fullname(String fullname) {
        try {
//            fullname = jTextField2.getText();
            if (fullname.length() > 0) {
                sql = "Select * from v2 where fullname like '" + fullname + "%'";
            } else if (fullname.length() == 0) {
                reset();
            }
            System.out.println(sql);
            model = (DefaultTableModel) jTable1.getModel();
            row = jTable1.getRowCount();
            if (row > 0) {
                for (int i = row - 1; i >= 0; i--) {
                    model.removeRow(i);
                }
            }
            rs =c.s.executeQuery(sql);
            System.out.println(sql);
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(9), rs.getString(10), rs.getString(12), rs.getString(7), rs.getString(11)});
            }
            jLabel3.setText(jTable1.getRowCount() + "");
//            data(fullname);
        } catch (SQLException e) {
            jOptionPane1.showMessageDialog(this, "Error is" + e, "Error", 0);
        }
    }

    void through_gender(String r1) {
        try {
//            String fullname = jTextField1.getText();
//            String address = jTextField2.getText();
//            sql = "Select * from v2 where fullname like = '" + fullname + "'or address='" + address + " or email='" + fullname + "'";
            sql = "Select * from v2 where gender ='" + r1 + "'";
            System.out.println(sql);
            model = (DefaultTableModel) jTable1.getModel();
            row = jTable1.getRowCount();
            if (row > 0) {
                for (int i = row - 1; i >= 0; i--) {
                    model.removeRow(i);
                }
            }
            rs = c.s.executeQuery(sql);
            System.out.println(sql);
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(9), rs.getString(10), rs.getString(12), rs.getString(7), rs.getString(11)});
            }
            jTable1.getRowCount();
//            data(r1);
        } catch (SQLException e) {
            jOptionPane1.showMessageDialog(this, "Error is" + e, "Error", 0);
        }
    }

    void through_department(String r1) {
        try {
//            String fullname = jTextField1.getText();
//            String address = jTextField2.getText();
            sql = "Select * from v2 where deptname ='" + r1 + "'";
            System.out.println(sql);
            model = (DefaultTableModel) jTable1.getModel();
            row = jTable1.getRowCount();
            if (row > 0) {
                for (int i = row - 1; i >= 0; i--) {
                    model.removeRow(i);
                }
            }
            rs = c.s.executeQuery(sql);
            System.out.println(sql);
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(9), rs.getString(10), rs.getString(12), rs.getString(7), rs.getString(11)});
            }
            jTable1.getRowCount();
//            data(r1);
        } catch (SQLException e) {
            jOptionPane1.showMessageDialog(this, "Error is" + e, "Error", 0);
        }
    }

    void through_jobstatus(String r1) {
        try {
//            String fullname = jTextField1.getText();
//            String address = jTextField2.getText();
            sql = "Select * from v2 where job_status ='" + r1 + "'";
            System.out.println(sql);
            model = (DefaultTableModel) jTable1.getModel();
            row = jTable1.getRowCount();
            if (row > 0) {
                for (int i = row - 1; i >= 0; i--) {
                    model.removeRow(i);
                }
            }
            rs = c.s.executeQuery(sql);
            System.out.println(sql);
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(9), rs.getString(10), rs.getString(12), rs.getString(7), rs.getString(11)});
            }
            jTable1.getRowCount();
//            data(r1);
        } catch (SQLException e) {
            jOptionPane1.showMessageDialog(this, "Error is" + e, "Error", 0);
        }
    }

    void getlist() {
        if (list == 0) {
            try {
                if (jLabel1.equals("EMPLOYEE ID :")) {
                    String empid = jTextField1.getText();
                    sql = "Select * from v2 where empid =" + empid + "";
                    System.out.println(sql);
                    model = (DefaultTableModel) jTable1.getModel();
                    row = jTable1.getRowCount();
                    if (row > 0) {
                        for (int i = row - 1; i >= 0; i--) {
                            model.removeRow(i);
                        }
                    }
                    rs = c.s.executeQuery(sql);
                    System.out.println(sql);
                    while (rs.next()) {
                        model.addRow(new Object[]{rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(9), rs.getString(10), rs.getString(12), rs.getString(7), rs.getString(11)});
                    }
                }
            } catch (SQLException e) {
                jOptionPane1.showMessageDialog(this, "Error is" + e, "Error", 0);
            }
        } else if (list == 1) {
            if (jRadioButton1.isSelected()) {
                r1 = jRadioButton1.getText();
            } else if (jRadioButton2.isSelected()) {
                r1 = jRadioButton2.getText();
            } else if (jRadioButton3.isSelected()) {
                r1 = jRadioButton3.getText();
            } else if (jRadioButton4.isSelected()) {
                r1 = jRadioButton4.getText();
            } else if (jRadioButton5.isSelected()) {
                r1 = jRadioButton5.getText();
            } else if (jRadioButton6.isSelected()) {
                r1 = jRadioButton6.getText();
            } else if (jRadioButton7.isSelected()) {
                r1 = jRadioButton7.getText();
            }
            through_salary(r1);
        } else if (list == 2) {
            if (jRadioButton1.isSelected()) {
                r1 = jRadioButton1.getText();
            } else if (jRadioButton2.isSelected()) {
                r1 = jRadioButton2.getText();
            } else if (jRadioButton3.isSelected()) {
                r1 = jRadioButton3.getText();
            } else if (jRadioButton4.isSelected()) {
                r1 = jRadioButton4.getText();
            } else if (jRadioButton5.isSelected()) {
                r1 = jRadioButton5.getText();
            } else if (jRadioButton6.isSelected()) {
                r1 = jRadioButton6.getText();
            } else if (jRadioButton7.isSelected()) {
                r1 = jRadioButton7.getText();
            } else if (jRadioButton8.isSelected()) {
                r1 = jRadioButton8.getText();
            }
            through_job(r1);
        } else if (list == 3) {
            if (jRadioButton1.isSelected()) {
                r1 = jRadioButton1.getText();
            } else if (jRadioButton2.isSelected()) {
                r1 = jRadioButton2.getText();
            } else if (jRadioButton3.isSelected()) {
                r1 = jRadioButton3.getText();
                through_gender(r1);
            } else if (list == 4) {
                if (jRadioButton1.isSelected()) {
                    r1 = jRadioButton1.getText();
                } else if (jRadioButton2.isSelected()) {
                    r1 = jRadioButton2.getText();
                } else if (jRadioButton3.isSelected()) {
                    r1 = jRadioButton3.getText();
                } else if (jRadioButton4.isSelected()) {
                    r1 = jRadioButton4.getText();
                } else if (jRadioButton5.isSelected()) {
                    r1 = jRadioButton5.getText();
                } else if (jRadioButton6.isSelected()) {
                    r1 = jRadioButton6.getText();
                } else if (jRadioButton7.isSelected()) {
                    r1 = jRadioButton7.getText();
                } else if (jRadioButton8.isSelected()) {
                    r1 = jRadioButton8.getText();
                }
                through_department(r1);
            } else if (list == 5) {
                if (jRadioButton1.isSelected()) {
                    r1 = jRadioButton1.getText();
                } else if (jRadioButton2.isSelected()) {
                    r1 = jRadioButton2.getText();
                } else if (jRadioButton3.isSelected()) {
                    r1 = jRadioButton3.getText();
                } else if (jRadioButton4.isSelected()) {
                    r1 = jRadioButton4.getText();
                } else if (jRadioButton5.isSelected()) {
                    r1 = jRadioButton5.getText();
                } else if (jRadioButton6.isSelected()) {
                    r1 = jRadioButton6.getText();
                } else if (jRadioButton7.isSelected()) {
                    r1 = jRadioButton7.getText();
                }
                through_jobstatus(r1);
            }
        }
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        getlist();
    }//GEN-LAST:event_jButton3ActionPerformed
    private void jRadioButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseClicked

    }//GEN-LAST:event_jRadioButton1MouseClicked

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed

    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jRadioButton1FocusLost

    }//GEN-LAST:event_jRadioButton1FocusLost

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed

    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed

    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        data("");
        jTextField1.requestFocus();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
       
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased

    }//GEN-LAST:event_jTextField2KeyReleased

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        String fullname = jTextField1.getText();
        if (evt.getKeyCode() == 10) {
            through_fullname(fullname);
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed

    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
        try {
            int empid = Integer.parseInt(jTextField3.getText());
            if (evt.getKeyCode() == 10) {
                through_empid(empid);
            }
        } catch (Exception e) {
            jOptionPane1.showMessageDialog(this, "Error is" + e, "Error", 0);
        }
    }//GEN-LAST:event_jTextField3KeyPressed
    void reset() {
        jPanel5.setVisible(false);
        jPanel7.setVisible(false);
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        data("");
        jTextField1.requestFocus();
    }
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        reset();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
        try {
            int empid = Integer.parseInt(jTextField3.getText());
            if (evt.getKeyCode() == 10) {
                through_empid(empid);
            }
        } catch (Exception e) {
            jOptionPane1.showMessageDialog(this, "Error is" + e, "Error", 0);
        }
    }//GEN-LAST:event_jTextField3KeyReleased

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        String address = jTextField2.getText();
        if (evt.getKeyCode() == 10) {
            through_Address(address);
        }
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusGained
     try
     {
         jTextField1.setText("");
         data("");
     }
     catch(Exception e)
     {
         jOptionPane1.showMessageDialog(this,"Error is"+e);
     }
    }//GEN-LAST:event_jTextField2FocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

    private void setLocationRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void function_RadioButton() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
