/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package Staff;

/**
 *
 * @author Ayush
 */
import java.sql.*;
import javax.swing.UIManager;

public class Staff_Parent_Frame extends javax.swing.JFrame {

    connect c;
    String sql;
//    static String username = Employee_login_page.user;
    static String pass = Employee_login_page.psw;

//    private final String username;
//    private final String password;
//    static String username, password;
    public Staff_Parent_Frame() {
        initComponents();
        c = new connect();
        c.getConnect();
        getcheck();
    }

    public void getcheck() {
        try {
            if (pass.equals(" ")) {
                jMenu1.setVisible(true);
                jMenu2.setVisible(true);
                jMenu3.setVisible(true);
                jMenu4.setVisible(true);
                jMenu5.setVisible(true);
                fileMenu.setVisible(true);
                Employee.setVisible(false);
                EmployeeLeave.setVisible(false);
                EmployeeAttendance.setVisible(false);
                CheckLeave.setVisible(false);

            } else {
                jMenu1.setVisible(false);
                jMenu2.setVisible(false);
                jMenu3.setVisible(false);
                jMenu4.setVisible(false);
                jMenu5.setVisible(false);
                fileMenu.setVisible(false);
                Employee.setVisible(true);
                EmployeeLeave.setVisible(true);
                EmployeeAttendance.setVisible(true);
                CheckLeave.setVisible(true);
            }
        } catch (Exception e) {
            jOptionPane1.showMessageDialog(this, "Error is" + e);
        }
    }

//    public void window() {
//        if (this.getFocusableWindowState()) {
//            jPanel1.setVisible(true);
//        }
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        cutMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        Employee = new javax.swing.JMenu();
        security = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        EmployeeLeave = new javax.swing.JMenu();
        EmployeeAttendance = new javax.swing.JMenu();
        CheckLeave = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setAutoscrolls(true);
        desktopPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fileMenu.setMnemonic('f');
        fileMenu.setText("DEPARTMENT");
        fileMenu.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N

        openMenuItem.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        openMenuItem.setMnemonic('o');
        openMenuItem.setText("ADD EMPLOYEE");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem);

        saveMenuItem.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("CHECK ATTENDANCE ");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("CHECK PAYMENT");
        saveAsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveAsMenuItem);

        cutMenuItem.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("RECORDS OF EMPLOYEE ");
        cutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(cutMenuItem);

        exitMenuItem.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("CH ECK LEAVE ");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        Employee.setMnemonic('e');
        Employee.setText("EMPLOYEE ");
        Employee.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N

        security.setText("LEAVE");
        security.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jMenuItem1.setText(" APPLY FOR LEAVE");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        security.add(jMenuItem1);

        Employee.add(security);

        jMenuItem2.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jMenuItem2.setText("CHECK YOUR ATTENDANCE");
        Employee.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jMenuItem3.setText(" CHECK YOUR LEAVE ");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        Employee.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jMenuItem4.setText("YOUR PAYMENT");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        Employee.add(jMenuItem4);

        menuBar.add(Employee);

        jMenu1.setText("ADD EMPLOYEE ");
        jMenu1.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        menuBar.add(jMenu1);

        jMenu2.setText("ATTENDANCE");
        jMenu2.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        menuBar.add(jMenu2);

        jMenu3.setText("PAYMENT");
        jMenu3.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        menuBar.add(jMenu3);

        jMenu4.setText("TOTAL RECORDS");
        jMenu4.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        menuBar.add(jMenu4);

        jMenu5.setText("LEAVE ");
        jMenu5.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        menuBar.add(jMenu5);

        EmployeeLeave.setText("EMP APPLY LEAVE");
        EmployeeLeave.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        menuBar.add(EmployeeLeave);

        EmployeeAttendance.setText("EMP ATTENDANCE");
        EmployeeAttendance.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        menuBar.add(EmployeeAttendance);

        CheckLeave.setText("EMP LEAVE");
        CheckLeave.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        menuBar.add(CheckLeave);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1546, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed

    }//GEN-LAST:event_exitMenuItemActionPerformed
    public void clearallpanel() {

    }
    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        Add_Employee add = new Add_Employee();
        add.setVisible(true);
        desktopPane.add(add);
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed

    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void saveAsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsMenuItemActionPerformed


    }//GEN-LAST:event_saveAsMenuItemActionPerformed

    private void cutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuItemActionPerformed
        Record_Employee e = new Record_Employee();
        e.setVisible(true);
        desktopPane.add(e);
    }//GEN-LAST:event_cutMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        EmployeeCheckLeave lv = new EmployeeCheckLeave();
        lv.setVisible(true);
        desktopPane.add(lv);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        AllLeaveRecord alr = new AllLeaveRecord();
        alr.setVisible(true);
        desktopPane.add(alr);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        payment p = new payment();
        p.setVisible(true);
        desktopPane.add(p);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Staff_Parent_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Staff_Parent_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Staff_Parent_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Staff_Parent_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Staff_Parent_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu CheckLeave;
    private javax.swing.JMenu Employee;
    private javax.swing.JMenu EmployeeAttendance;
    private javax.swing.JMenu EmployeeLeave;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JMenu security;
    // End of variables declaration//GEN-END:variables

}
